apps:
  - name: cost-flow-ortools
    language: python
    language-version: 3.11
  - name: knapsack-ampl
    language: python
    language-version: 3.11
  - name: knapsack-gosdk
    language: go
    language-version: 1.22
  - name: knapsack-gurobi
    language: python
    language-version: 3.11
  - name: knapsack-java-ortools
    language: java
    language-version: 21
    distribution: temurin
  - name: knapsack-ortools
    language: python
    language-version: 3.11
  - name: knapsack-pyomo
    language: python
    language-version: 3.11
  - name: nextroute
    language: go
    language-version: 1.22
  - name: order-fulfillment-gosdk
    language: go
    language-version: 1.22
  - name: routing-ortools
    language: python
    language-version: 3.11
  - name: shift-assignment-ortools
    language: python
    language-version: 3.11
  - name: shift-assignment-pyomo
    language: python
    language-version: 3.11
  - name: shift-planning-ortools
    language: python
    language-version: 3.11
  - name: shift-planning-pyomo
    language: python
    language-version: 3.11
  - name: shift-scheduling-gosdk
    language: go
    language-version: 1.22
  - name: xpress
    language: python
    language-version: 3.11
